// Sin & Punishment: Recompiled — native PC port via N64Recomp + RT64.
// Minimal launcher: boots the game to the title screen (Fase 2 milestone).
// Pattern follows BanjoRecomp's src/main/main.cpp and N64ModernRuntime's API.

#include <cstdio>
#include <cassert>
#include <vector>
#include <string>
#include <cinttypes>
#include <filesystem>

#define SDL_MAIN_HANDLED
#ifdef _WIN32
#include "SDL.h"
#else
#include "SDL2/SDL.h"
#include "SDL2/SDL_syswm.h"
#undef None
#undef Status
#endif

#include "ultramodern/ultra64.h"
#include "ultramodern/ultramodern.hpp"
#include "librecomp/game.hpp"
#include "librecomp/rsp.hpp"
#include "recompui/renderer.h"
#include "recompui/recompui.h"
#include "recompui/program_config.h"
#include "recompui/config.h"
#include "util/file.h"
#include "recompinput/input_state.h"
#include "recompinput/input_events.h"
#include "recompinput/profiles.h"
#include "recompinput/players.h"

const std::string version_string = "0.1.0";
const std::string program_name = "Sin & Punishment: Recompiled";
const std::u8string program_id = u8"sinpunishment";

// Global window pointer used by recompui (contract: game main must define a
// global `window` symbol; recompui/src/base/ui_state.cpp declares it extern).
SDL_Window* window = nullptr;

// ---------------------------------------------------------------------------
// RSP microcode callbacks (generated by RSPRecomp, see rsp/*.toml)
// Only the audio ucode needs recompiling: RT64 interprets gfx tasks natively
// (rt64_render_context.cpp send_dl -> loadUCodeGBI + processDisplayLists), so
// M_GFXTASK never reaches recomp::rsp::run_task.
// ---------------------------------------------------------------------------
extern RspUcodeFunc n_aspMain;      // custom audio microcode (rsp/audio.toml)

static RspUcodeFunc* get_rsp_microcode(const OSTask* task) {
    switch (task->t.type) {
        case M_AUDTASK:
            return &n_aspMain;
        default:
            fprintf(stderr, "Unknown RSP task type: %" PRIu32 "\n", task->t.type);
            return nullptr;
    }
}

// ---------------------------------------------------------------------------
// Graphics callbacks (SDL2 window + RT64 render context via recompui)
// ---------------------------------------------------------------------------
ultramodern::gfx_callbacks_t::gfx_data_t create_gfx() {
    SDL_SetHint(SDL_HINT_WINDOWS_DPI_AWARENESS, "permonitorv2");
    SDL_SetHint(SDL_HINT_GAMECONTROLLER_USE_BUTTON_LABELS, "0");

    if (SDL_Init(SDL_INIT_VIDEO | SDL_INIT_GAMECONTROLLER | SDL_INIT_JOYSTICK | SDL_INIT_HAPTIC) != 0) {
        fprintf(stderr, "Failed to initialize SDL2: %s\n", SDL_GetError());
        assert(false);
    }
    fprintf(stdout, "SDL Video Driver: %s\n", SDL_GetCurrentVideoDriver());
    return nullptr;
}

ultramodern::renderer::WindowHandle create_window(ultramodern::gfx_callbacks_t::gfx_data_t) {
    SDL_Window* sdl_window = SDL_CreateWindow(
        "Sin & Punishment: Recompiled",
        SDL_WINDOWPOS_CENTERED, SDL_WINDOWPOS_CENTERED,
        1280, 720,
        SDL_WINDOW_RESIZABLE | SDL_WINDOW_ALLOW_HIGHDPI
    );
    if (sdl_window == nullptr) {
        fprintf(stderr, "Failed to create SDL window: %s\n", SDL_GetError());
        assert(false);
    }
    ::window = sdl_window;  // publish for recompui
#ifdef __APPLE__
    // RT64's Metal backend needs the NSWindow and its Metal layer (CAMetalLayer).
    SDL_SysWMinfo wmInfo{};
    SDL_VERSION(&wmInfo.version);
    if (SDL_GetWindowWMInfo(sdl_window, &wmInfo) == 0) {
        fprintf(stderr, "Failed to get window WM info: %s\n", SDL_GetError());
        assert(false);
    }
    SDL_MetalView metal_view = SDL_Metal_CreateView(sdl_window);
    return ultramodern::renderer::WindowHandle{
        .window = wmInfo.info.cocoa.window,
        .view = SDL_Metal_GetLayer(metal_view),
    };
#else
    return ultramodern::renderer::WindowHandle{ sdl_window };
#endif
}

void update_gfx(ultramodern::gfx_callbacks_t::gfx_data_t) {
    recompinput::handle_events();
}

// ---------------------------------------------------------------------------
// Audio callbacks (minimal SDL audio queue for Fase 2; full mixer later)
// ---------------------------------------------------------------------------
static SDL_AudioDeviceID audio_device = 0;

void queue_samples(int16_t* samples, size_t count) {
    if (audio_device != 0) {
        SDL_QueueAudio(audio_device, samples, (Uint32)(count * sizeof(int16_t)));
    }
}

size_t get_frames_remaining() {
    if (audio_device == 0) {
        return 0;
    }
    return SDL_GetQueuedAudioSize(audio_device) / sizeof(int16_t);
}

void set_frequency(uint32_t freq) {
    if (audio_device != 0) {
        SDL_CloseAudioDevice(audio_device);
        audio_device = 0;
    }
    SDL_AudioSpec spec{};
    spec.freq = (int)freq;
    spec.format = AUDIO_S16SYS;
    spec.channels = 2;
    spec.samples = 0x100;
    audio_device = SDL_OpenAudioDevice(nullptr, 0, &spec, nullptr, 0);
    if (audio_device == 0) {
        fprintf(stderr, "Failed to open audio device: %s\n", SDL_GetError());
    } else {
        SDL_PauseAudioDevice(audio_device, 0);
    }
}

// ---------------------------------------------------------------------------
// Input callbacks (minimal: no input yet in Fase 2, wired in Fase 3)
// ---------------------------------------------------------------------------
static void poll_input() {
    recompinput::poll_inputs();
}
static bool get_input(int controller_num, uint16_t* buttons, float* x, float* y) {
    return recompinput::profiles::get_n64_input(controller_num, buttons, x, y);
}
static void set_rumble(int controller_num, bool on) {
    recompinput::set_rumble(controller_num, on);
}
static ultramodern::input::connected_device_info_t get_connected_device_info(int controller_num) {
    if (recompinput::players::is_single_player_mode() || recompinput::players::get_player_is_assigned(controller_num)) {
        return ultramodern::input::connected_device_info_t{
            .connected_device = ultramodern::input::Device::Controller,
            .connected_pak = ultramodern::input::Pak::RumblePak,
        };
    }
    return ultramodern::input::connected_device_info_t{
        .connected_device = ultramodern::input::Device::None,
        .connected_pak = ultramodern::input::Pak::None,
    };
}


// ---------------------------------------------------------------------------
// Entry point address (generated by N64Recomp into RecompiledFuncs/recomp.h)
// ---------------------------------------------------------------------------
extern "C" void recomp_entrypoint(uint8_t* rdram, recomp_context* ctx);
gpr get_entrypoint_address();

// ---------------------------------------------------------------------------
// Game entry
// ---------------------------------------------------------------------------
std::vector<recomp::GameEntry> supported_games = {
    {
        .rom_hash = 0xEC641B62243B72B9ULL,   // XXH3-64 of rom/sinpunishment.z64
        .internal_name = "TSUMI TO BATSU",
        .display_name = "Sin & Punishment",
        .game_id = u8"sinpunishment.n64.jp.1.0",
        .mod_game_id = "sinpunishment",
        .save_type = recomp::SaveType::None,
        .is_enabled = true,
        .entrypoint_address = get_entrypoint_address(),
        .entrypoint = recomp_entrypoint,
    },
};

static void init_config() {
    std::filesystem::path recomp_dir = recompui::file::get_app_folder_path();
    if (!recomp_dir.empty()) {
        std::filesystem::create_directories(recomp_dir);
    }

    recompui::config::GeneralTabOptions general_options{};
    general_options.has_rumble_strength = false;
    general_options.has_gyro_sensitivity = false;
    general_options.has_mouse_sensitivity = false;

    recompui::config::create_general_tab(general_options);
    recompui::config::create_graphics_tab();
    recompui::config::create_controls_tab();
    recompui::config::create_sound_tab();
    recompui::config::create_mods_tab();

    recompui::config::finalize();
}

int main(int argc, char** argv) {
    (void)argc; (void)argv;

    // SDL audio init
    SDL_InitSubSystem(SDL_INIT_AUDIO);

    recomp::rsp::callbacks_t rsp_callbacks{
        .get_rsp_microcode = get_rsp_microcode,
    };

    ultramodern::renderer::callbacks_t renderer_callbacks{
        .create_render_context = [](uint8_t* rdram, ultramodern::renderer::WindowHandle window_handle, bool developer_mode) {
            auto presentation_mode = ultramodern::renderer::PresentationMode::PresentEarly;
            return recompui::renderer::create_render_context(rdram, window_handle, presentation_mode, developer_mode);
        },
    };

    ultramodern::gfx_callbacks_t gfx_callbacks{
        .create_gfx = create_gfx,
        .create_window = create_window,
        .update_gfx = update_gfx,
    };

    ultramodern::audio_callbacks_t audio_callbacks{
        .queue_samples = queue_samples,
        .get_frames_remaining = get_frames_remaining,
        .set_frequency = set_frequency,
    };

    ultramodern::input::callbacks_t input_callbacks{
        .poll_input = poll_input,
        .get_input = get_input,
        .set_rumble = set_rumble,
        .get_connected_device_info = get_connected_device_info,
    };

    ultramodern::events::callbacks_t events_callbacks{
        .vi_callback = nullptr,
        .gfx_init_callback = nullptr,
    };

    ultramodern::error_handling::callbacks_t error_handling_callbacks{
        .message_box = [](const char* msg) {
            fprintf(stderr, "Error: %s\n", msg);
            SDL_ShowSimpleMessageBox(SDL_MESSAGEBOX_ERROR, "Sin & Punishment: Recompiled", msg, nullptr);
        },
    };

    ultramodern::threads::callbacks_t threads_callbacks{
        .get_game_thread_name = [](const OSThread* t) -> std::string {
            return "[Game] " + std::to_string(t->id);
        },
    };

    recomp::Version project_version{};
    if (!recomp::Version::from_string(version_string, project_version)) {
        fprintf(stderr, "Invalid version string\n");
        return EXIT_FAILURE;
    }

    // Initialize program settings for recompui (must be set before any
    // recompui::file::* call, which uses the program id for paths).
    recompui::programconfig::set_program_name(program_name);
    recompui::programconfig::set_program_id(program_id);

    recomp::register_config_path(recompui::file::get_app_folder_path());

    for (const auto& game : supported_games) {
        recomp::register_game(game);
    }

    // Developer/testing hook: SP_AUTOSTART=1 starts the game immediately,
    // skipping the launcher (useful for automated boot testing).
    if (getenv("SP_AUTOSTART") != nullptr) {
        recompui::register_launcher_init_callback([](recompui::LauncherMenu* menu) {
            (void)menu;
            recomp::start_game(supported_games[0].game_id, {});
        });
    }

    // Register fonts for recompui (must exist under assets/ next to the executable).
    recompui::register_primary_font("InterVariable.ttf", "Inter Variable");
    recompui::register_extra_font("NotoEmoji-Regular.ttf");

    // Initialize config (creates tabs + loads from disk).
    init_config();

    recomp::Configuration config{
        .project_version = project_version,
        .window_handle = {},
        .rsp_callbacks = rsp_callbacks,
        .renderer_callbacks = renderer_callbacks,
        .audio_callbacks = audio_callbacks,
        .input_callbacks = input_callbacks,
        .gfx_callbacks = gfx_callbacks,
        .events_callbacks = events_callbacks,
        .error_handling_callbacks = error_handling_callbacks,
        .threads_callbacks = threads_callbacks,
        .message_queue_control = {},
    };

    recomp::start(config);
    return EXIT_SUCCESS;
}
