// Sin & Punishment: Recompiled — native PC port via N64Recomp + RT64.
// Minimal launcher: boots the game to the title screen (Fase 2 milestone).
// Pattern follows BanjoRecomp's src/main/main.cpp and N64ModernRuntime's API.

#include <cstdio>
#include <cassert>
#include <vector>
#include <string>
#include <cinttypes>
#include <cstring>
#include <cmath>
#include <array>
#include <algorithm>
#include <chrono>
#include <filesystem>

#define SDL_MAIN_HANDLED
#ifdef _WIN32
#include "SDL.h"
#else
#include "SDL2/SDL.h"
#include "SDL2/SDL_syswm.h"
#undef None
#undef Status
#endif

#include "ultramodern/ultra64.h"
#include "ultramodern/ultramodern.hpp"
#include "librecomp/game.hpp"
#include "librecomp/rsp.hpp"
#include "recompui/renderer.h"
#include "recompui/recompui.h"
#include "recompui/program_config.h"
#include "recompui/config.h"
#include "util/file.h"
#include "recompinput/input_state.h"
#include "recompinput/input_events.h"
#include "recompinput/profiles.h"
#include "recompinput/players.h"

const std::string version_string = "0.1.0";
const std::string program_name = "Sin & Punishment: Recompiled";
const std::u8string program_id = u8"sinpunishment";

// Global window pointer used by recompui (contract: game main must define a
// global `window` symbol; recompui/src/base/ui_state.cpp declares it extern).
SDL_Window* window = nullptr;

// ---------------------------------------------------------------------------
// Syscall handler (emitted by N64Recomp for MIPS `syscall` instructions).
// The runtime has no syscall support; Sin & Punishment only contains one
// syscall inside a misidentified vector/trampoline (ovl5_func_8014C754) that
// is never dispatched to, so a logging stub suffices.
// ---------------------------------------------------------------------------
extern "C" void recomp_syscall_handler(uint8_t* rdram, recomp_context* ctx, int32_t instruction_vram) {
    (void)rdram; (void)ctx;
    fprintf(stderr, "recomp_syscall_handler: unhandled syscall at 0x%08X\n", instruction_vram);
}

// ---------------------------------------------------------------------------
// RSP microcode callbacks (generated by RSPRecomp, see rsp/*.toml)
// Only the audio ucode needs recompiling: RT64 interprets gfx tasks natively
// (rt64_render_context.cpp send_dl -> loadUCodeGBI + processDisplayLists), so
// M_GFXTASK never reaches recomp::rsp::run_task.
// ---------------------------------------------------------------------------
extern RspUcodeFunc n_aspMain;      // custom audio microcode (rsp/audio.toml)

static RspUcodeFunc* get_rsp_microcode(const OSTask* task) {
    switch (task->t.type) {
        case M_AUDTASK:
            return &n_aspMain;
        default:
            fprintf(stderr, "Unknown RSP task type: %" PRIu32 "\n", task->t.type);
            return nullptr;
    }
}

// ---------------------------------------------------------------------------
// Graphics callbacks (SDL2 window + RT64 render context via recompui)
// ---------------------------------------------------------------------------
ultramodern::gfx_callbacks_t::gfx_data_t create_gfx() {
    SDL_SetHint(SDL_HINT_WINDOWS_DPI_AWARENESS, "permonitorv2");
    SDL_SetHint(SDL_HINT_GAMECONTROLLER_USE_BUTTON_LABELS, "0");

    if (SDL_Init(SDL_INIT_VIDEO | SDL_INIT_GAMECONTROLLER | SDL_INIT_JOYSTICK | SDL_INIT_HAPTIC) != 0) {
        fprintf(stderr, "Failed to initialize SDL2: %s\n", SDL_GetError());
        assert(false);
    }
    fprintf(stdout, "SDL Video Driver: %s\n", SDL_GetCurrentVideoDriver());
    return nullptr;
}

ultramodern::renderer::WindowHandle create_window(ultramodern::gfx_callbacks_t::gfx_data_t) {
    SDL_Window* sdl_window = SDL_CreateWindow(
        "Sin & Punishment: Recompiled",
        SDL_WINDOWPOS_CENTERED, SDL_WINDOWPOS_CENTERED,
        1280, 720,
        SDL_WINDOW_RESIZABLE | SDL_WINDOW_ALLOW_HIGHDPI
    );
    if (sdl_window == nullptr) {
        fprintf(stderr, "Failed to create SDL window: %s\n", SDL_GetError());
        assert(false);
    }
    ::window = sdl_window;  // publish for recompui

    // Honor the persisted window mode (graphics.json wm_option) at startup. Without this the
    // window always opens windowed: RT64 only applies wm_option when it *changes* at runtime
    // (update_config diff), so a saved Fullscreen preference was never applied on relaunch.
    {
        recomp::config::ConfigValueVariant wm_value =
            recompui::config::get_graphics_config().get_option_value(recompui::config::graphics::options::wm_option);
        if (const auto* wm = std::get_if<uint32_t>(&wm_value);
            wm != nullptr && static_cast<ultramodern::renderer::WindowMode>(*wm) == ultramodern::renderer::WindowMode::Fullscreen) {
            if (SDL_SetWindowFullscreen(sdl_window, SDL_WINDOW_FULLSCREEN_DESKTOP) != 0) {
                fprintf(stderr, "Failed to set fullscreen from config: %s\n", SDL_GetError());
            }
        }
    }
#ifdef __APPLE__
    // RT64's Metal backend needs the NSWindow and its Metal layer (CAMetalLayer).
    SDL_SysWMinfo wmInfo{};
    SDL_VERSION(&wmInfo.version);
    if (SDL_GetWindowWMInfo(sdl_window, &wmInfo) == 0) {
        fprintf(stderr, "Failed to get window WM info: %s\n", SDL_GetError());
        assert(false);
    }
    SDL_MetalView metal_view = SDL_Metal_CreateView(sdl_window);
    return ultramodern::renderer::WindowHandle{
        .window = wmInfo.info.cocoa.window,
        .view = SDL_Metal_GetLayer(metal_view),
    };
#else
    return ultramodern::renderer::WindowHandle{ sdl_window };
#endif
}

void update_gfx(ultramodern::gfx_callbacks_t::gfx_data_t) {
    recompinput::handle_events();
}

// ---------------------------------------------------------------------------
// Audio callbacks (minimal SDL audio queue for Fase 2; full mixer later)
// ---------------------------------------------------------------------------
// [ws3-audio] debug instrumentation, env-gated (no effect on normal runs):
//   SNP_AUDIO_DUMP=<path>  tee every queued sample (int16 LE, stereo) to a raw
//                          file for offline analysis (underruns, content, pops)
//   SNP_TRACE=1            log set_frequency changes, queue depths, underruns
static SDL_AudioDeviceID audio_device = 0;
static FILE* audio_dump_file = nullptr;
static uint64_t audio_queue_call_count = 0;
static uint64_t audio_total_samples_queued = 0;
static size_t audio_min_depth_before = SIZE_MAX;

void queue_samples(int16_t* samples, size_t count) {
    if (audio_device != 0) {
        if (audio_dump_file == nullptr) {
            const char* dump_path = getenv("SNP_AUDIO_DUMP");
            if (dump_path != nullptr) {
                audio_dump_file = fopen(dump_path, "wb");
                if (audio_dump_file != nullptr) {
                    fprintf(stderr, "[audio] dumping samples to %s\n", dump_path);
                }
            }
        }
        if (audio_dump_file != nullptr) {
            fwrite(samples, sizeof(int16_t), count, audio_dump_file);
            audio_total_samples_queued += count;
            if (audio_total_samples_queued % 44100 == 0) {
                fflush(audio_dump_file);
            }
        }
        Uint32 depth_before = SDL_GetQueuedAudioSize(audio_device);
        if (depth_before < audio_min_depth_before) {
            audio_min_depth_before = depth_before;
        }
        SDL_QueueAudio(audio_device, samples, (Uint32)(count * sizeof(int16_t)));
        audio_queue_call_count++;
        if (getenv("SNP_TRACE") != nullptr) {
            if (audio_queue_call_count <= 20 || (audio_queue_call_count % 4096) == 0) {
                fprintf(stderr, "[audio] queue_samples #%llu count=%zu depth_before=%u depth_after=%u min=%zu total_samples=%llu\n",
                        (unsigned long long)audio_queue_call_count, count, (unsigned)depth_before,
                        (unsigned)SDL_GetQueuedAudioSize(audio_device), audio_min_depth_before,
                        (unsigned long long)audio_total_samples_queued);
            }
            // Near-empty queue when a new buffer arrives = the SDL queue drained
            // to silence between refills -> audible pop. Log every occurrence
            // (rate-limited to every 64th call when the queue is chronically low).
            if (depth_before < 4096) {
                static uint64_t low_queue_last_logged = 0;
                if (audio_queue_call_count - low_queue_last_logged >= 64) {
                    fprintf(stderr, "[audio] LOW-QUEUE #%llu depth_before=%u bytes (%zu samples, ~%.1f ms at 44.1kHz) -> underrun risk\n",
                            (unsigned long long)audio_queue_call_count, (unsigned)depth_before,
                            (size_t)(depth_before / 2), (double)(depth_before / 2) / 44.1);
                    low_queue_last_logged = audio_queue_call_count;
                }
            }
        }
    }
}

size_t get_frames_remaining() {
    if (audio_device == 0) {
        return 0;
    }
    return SDL_GetQueuedAudioSize(audio_device) / sizeof(int16_t);
}

void set_frequency(uint32_t freq) {
    if (getenv("SNP_TRACE") != nullptr) {
        fprintf(stderr, "[audio] set_frequency(%u)\n", freq);
    }
    if (audio_device != 0) {
        SDL_CloseAudioDevice(audio_device);
        audio_device = 0;
    }
    SDL_AudioSpec spec{};
    spec.freq = (int)freq;
    spec.format = AUDIO_S16SYS;
    spec.channels = 2;
    spec.samples = 0x100;
    audio_device = SDL_OpenAudioDevice(nullptr, 0, &spec, nullptr, 0);
    if (audio_device == 0) {
        fprintf(stderr, "Failed to open audio device: %s\n", SDL_GetError());
    } else {
        fprintf(stderr, "[audio] device open: freq=%d channels=%d samples=%u\n", spec.freq, spec.channels, spec.samples);
        SDL_PauseAudioDevice(audio_device, 0);
    }
}

// ---------------------------------------------------------------------------
// Input callbacks (Fase 3 / WS1): wired to recompinput (profiles, bindings).
// Mouse aiming: recompinput captures raw mouse deltas (add_mouse_deltas) but
// does NOT convert them to the N64 stick (InputType::Mouse is a TODO that
// returns 0). For a stick-aim rail shooter we integrate the deltas into a
// virtual stick at the port boundary, enabled by the General tab's
// "Mouse Sensitivity" option (> 0). Keyboard/controller paths unchanged.
// Dev/test hook: SP_INPUT_SCRIPT=<file> feeds timed synthetic input at the
// port boundary (same path real input takes), used for headless verification:
//   t=<seconds> keydown <NAME> | keyup <NAME> | stick <x> <y>
//   NAME: A B Z L R START C_UP C_DOWN C_LEFT C_RIGHT DPAD_* (0x8000/0x4000/...)
// ---------------------------------------------------------------------------

// Virtual stick fed by the mouse (decays back to center when the mouse stops).
static std::array<float, 2> mouse_aim_stick{ 0.0f, 0.0f };

static bool mouse_aiming_enabled() {
    if (!recompui::config::general::has_mouse_sensitivity_option()) {
        return false;
    }
    return recompui::config::general::get_mouse_sensitivity() > 0.0;
}

static void poll_input() {
    recompinput::poll_inputs();

    // Integrate the mouse deltas accumulated since the last poll into a
    // decaying virtual stick. Screen-space Y is inverted (up = positive stick).
    if (mouse_aiming_enabled() && !recompinput::game_input_disabled()) {
        float dx = 0.0f, dy = 0.0f;
        recompinput::get_mouse_deltas(&dx, &dy);
        // kDecay: stick returns to center in ~0.1s after the mouse stops.
        // kScale: pixel delta per frame -> stick units (tuned for 60 fps).
        constexpr float kDecay = 0.70f;
        constexpr float kScale = 0.012f;
        float sens = (float)(recompui::config::general::get_mouse_sensitivity() / 100.0);
        mouse_aim_stick[0] = mouse_aim_stick[0] * kDecay + dx * kScale * sens;
        mouse_aim_stick[1] = mouse_aim_stick[1] * kDecay - dy * kScale * sens;
    } else {
        mouse_aim_stick = { 0.0f, 0.0f };
    }
}

// --- SP_INPUT_SCRIPT (dev/test hook, see header comment) --------------------
struct ScriptedInputState {
    struct Event {
        double t;
        bool keydown;      // true = keydown, false = keyup
        uint16_t button;   // N64 button bit (0 = stick event)
        float sx, sy;      // stick value for stick events
        bool mouse_delta;  // true = feed synthetic mouse delta (test path)
    };
    std::vector<Event> events{};
    size_t next = 0;
    bool loaded = false;
    std::chrono::steady_clock::time_point t0{};
    uint16_t buttons = 0;
    bool stick_set = false;
    float sx = 0.0f, sy = 0.0f;
};

static ScriptedInputState g_scripted_input;

static uint16_t script_button_bit(const char* name) {
    struct { const char* name; uint16_t bit; } table[] = {
        { "A", 0x8000 }, { "B", 0x4000 }, { "Z", 0x2000 }, { "L", 0x0020 },
        { "R", 0x0010 }, { "START", 0x1000 }, { "C_UP", 0x0008 },
        { "C_DOWN", 0x0004 }, { "C_LEFT", 0x0002 }, { "C_RIGHT", 0x0001 },
        { "DPAD_UP", 0x0800 }, { "DPAD_DOWN", 0x0400 }, { "DPAD_LEFT", 0x0200 },
        { "DPAD_RIGHT", 0x0100 },
    };
    for (const auto& entry : table) {
        if (strcmp(name, entry.name) == 0) {
            return entry.bit;
        }
    }
    return 0;
}

static void load_input_script() {
    const char* path = getenv("SP_INPUT_SCRIPT");
    if (path == nullptr) {
        return;
    }
    FILE* f = fopen(path, "r");
    if (f == nullptr) {
        fprintf(stderr, "[input-script] warning: cannot open %s\n", path);
        return;
    }
    char line[256];
    int line_no = 0;
    while (fgets(line, sizeof(line), f)) {
        line_no++;
        char* comment = strchr(line, '#');
        if (comment != nullptr) {
            *comment = '\0';
        }
        double t = 0.0;
        char cmd[64] = { 0 };
        if (sscanf(line, " t=%lf %63s", &t, cmd) < 2) {
            continue;
        }
        ScriptedInputState::Event ev{};
        ev.t = t;
        if (strcmp(cmd, "keydown") == 0 || strcmp(cmd, "keyup") == 0) {
            char name[32] = { 0 };
            if (sscanf(line, " t=%lf %63s %31s", &t, cmd, name) < 3) {
                fprintf(stderr, "[input-script] %s:%d: bad key event\n", path, line_no);
                continue;
            }
            ev.keydown = strcmp(cmd, "keydown") == 0;
            ev.button = script_button_bit(name);
            if (ev.button == 0) {
                fprintf(stderr, "[input-script] %s:%d: unknown key '%s'\n", path, line_no, name);
                continue;
            }
        } else if (strcmp(cmd, "stick") == 0) {
            if (sscanf(line, " t=%lf %63s %f %f", &t, cmd, &ev.sx, &ev.sy) < 4) {
                fprintf(stderr, "[input-script] %s:%d: bad stick event\n", path, line_no);
                continue;
            }
            ev.sx = std::clamp(ev.sx, -1.0f, 1.0f);
            ev.sy = std::clamp(ev.sy, -1.0f, 1.0f);
        } else if (strcmp(cmd, "mousedelta") == 0) {
            // Feeds recompinput::add_mouse_deltas (the real SDL_MOUSEMOTION
            // path) so the poll_input mouse->stick integration is exercised.
            if (sscanf(line, " t=%lf %63s %f %f", &t, cmd, &ev.sx, &ev.sy) < 4) {
                fprintf(stderr, "[input-script] %s:%d: bad mousedelta event\n", path, line_no);
                continue;
            }
            ev.mouse_delta = true;
        } else {
            fprintf(stderr, "[input-script] %s:%d: unknown command '%s'\n", path, line_no, cmd);
            continue;
        }
        g_scripted_input.events.emplace_back(ev);
    }
    fclose(f);
    std::sort(g_scripted_input.events.begin(), g_scripted_input.events.end(),
              [](const auto& a, const auto& b) { return a.t < b.t; });
    g_scripted_input.loaded = !g_scripted_input.events.empty();
    g_scripted_input.t0 = std::chrono::steady_clock::now();
    fprintf(stderr, "[input-script] loaded %zu events from %s\n", g_scripted_input.events.size(), path);
}

// Apply scripted events whose timestamp has elapsed; returns true if state changed.
static bool update_scripted_input() {
    if (!g_scripted_input.loaded) {
        return false;
    }
    double elapsed = std::chrono::duration<double>(std::chrono::steady_clock::now() - g_scripted_input.t0).count();
    bool changed = false;
    while (g_scripted_input.next < g_scripted_input.events.size() &&
           g_scripted_input.events[g_scripted_input.next].t <= elapsed) {
        const auto& ev = g_scripted_input.events[g_scripted_input.next++];
        if (ev.button != 0) {
            if (ev.keydown) {
                g_scripted_input.buttons |= ev.button;
            } else {
                g_scripted_input.buttons &= (uint16_t)~ev.button;
            }
            fprintf(stderr, "[input-script] t=%.2f %s %04X (buttons now %04X)\n",
                    ev.t, ev.keydown ? "keydown" : "keyup", ev.button, g_scripted_input.buttons);
        } else if (ev.mouse_delta) {
            recompinput::add_mouse_deltas(ev.sx, ev.sy);
            fprintf(stderr, "[input-script] t=%.2f mousedelta %.2f %.2f\n", ev.t, ev.sx, ev.sy);
        } else {
            g_scripted_input.stick_set = true;
            g_scripted_input.sx = ev.sx;
            g_scripted_input.sy = ev.sy;
            fprintf(stderr, "[input-script] t=%.2f stick %.2f %.2f\n", ev.t, ev.sx, ev.sy);
        }
        changed = true;
    }
    return changed;
}

static void maybe_log_input(int controller_num, uint16_t buttons, float x, float y) {
    if (getenv("SNP_TRACE") == nullptr) {
        return;
    }
    static uint16_t prev_buttons = 0;
    static float prev_x = 0.0f, prev_y = 0.0f;
    if (buttons != prev_buttons || fabsf(x - prev_x) > 0.01f || fabsf(y - prev_y) > 0.01f) {
        fprintf(stderr, "[input] ch=%d buttons=%04X stick=%.3f,%.3f\n", controller_num, buttons, x, y);
    }
    prev_buttons = buttons;
    prev_x = x;
    prev_y = y;
}

static bool get_input(int controller_num, uint16_t* buttons, float* x, float* y) {
    bool ok = recompinput::profiles::get_n64_input(controller_num, buttons, x, y);

    // Mouse aiming (player 1 only; deltas already integrated once per poll).
    if (ok && controller_num == 0 && mouse_aiming_enabled() && !recompinput::game_input_disabled()) {
        *x = std::clamp(*x + mouse_aim_stick[0], -1.0f, 1.0f);
        *y = std::clamp(*y + mouse_aim_stick[1], -1.0f, 1.0f);
    }

    // SP_INPUT_SCRIPT dev hook (player 1 only): OR scripted buttons, override stick.
    if (ok && controller_num == 0 && g_scripted_input.loaded) {
        update_scripted_input();
        *buttons |= g_scripted_input.buttons;
        if (g_scripted_input.stick_set) {
            *x = g_scripted_input.sx;
            *y = g_scripted_input.sy;
        }
    }

    maybe_log_input(controller_num, *buttons, *x, *y);
    return ok;
}
static void set_rumble(int controller_num, bool on) {
    recompinput::set_rumble(controller_num, on);
}
static ultramodern::input::connected_device_info_t get_connected_device_info(int controller_num) {
    if (recompinput::players::is_single_player_mode() || recompinput::players::get_player_is_assigned(controller_num)) {
        return ultramodern::input::connected_device_info_t{
            .connected_device = ultramodern::input::Device::Controller,
            .connected_pak = ultramodern::input::Pak::RumblePak,
        };
    }
    return ultramodern::input::connected_device_info_t{
        .connected_device = ultramodern::input::Device::None,
        .connected_pak = ultramodern::input::Pak::None,
    };
}


// ---------------------------------------------------------------------------
// Entry point address (generated by N64Recomp into RecompiledFuncs/recomp.h)
// ---------------------------------------------------------------------------
extern "C" void recomp_entrypoint(uint8_t* rdram, recomp_context* ctx);
gpr get_entrypoint_address();
void register_snp_overlays();

// ---------------------------------------------------------------------------
// Game entry
// ---------------------------------------------------------------------------
std::vector<recomp::GameEntry> supported_games = {
    {
        .rom_hash = 0xEC641B62243B72B9ULL,   // XXH3-64 of rom/sinpunishment.z64
        .internal_name = "TSUMI TO BATSU",
        .display_name = "Sin & Punishment",
        .game_id = u8"sinpunishment.n64.jp.1.0",
        .mod_game_id = "sinpunishment",
        .save_type = recomp::SaveType::None,
        .is_enabled = true,
        .entrypoint_address = get_entrypoint_address(),
        .entrypoint = recomp_entrypoint,
    },
};

static void init_config() {
    std::filesystem::path recomp_dir = recompui::file::get_app_folder_path();
    if (!recomp_dir.empty()) {
        std::filesystem::create_directories(recomp_dir);
    }

    recompui::config::GeneralTabOptions general_options{};
    general_options.has_rumble_strength = false;
    general_options.has_gyro_sensitivity = false;
    // WS1: mouse aiming is wired at the port boundary (poll_input/get_input).
    // The slider shows in the General tab; 0 disables it (desktop default),
    // >0 enables mouse->stick aiming (cursor locks during gameplay).
    general_options.has_mouse_sensitivity = true;

    recompui::config::create_general_tab(general_options);
    recompui::config::create_graphics_tab();
    recompui::config::create_controls_tab();
    recompui::config::create_sound_tab();
    recompui::config::create_mods_tab();

    recompui::config::finalize();
}

int main(int argc, char** argv) {
    (void)argc; (void)argv;

    // SDL audio init
    SDL_InitSubSystem(SDL_INIT_AUDIO);

    recomp::rsp::callbacks_t rsp_callbacks{
        .get_rsp_microcode = get_rsp_microcode,
    };

    ultramodern::renderer::callbacks_t renderer_callbacks{
        .create_render_context = [](uint8_t* rdram, ultramodern::renderer::WindowHandle window_handle, bool developer_mode) {
            auto presentation_mode = ultramodern::renderer::PresentationMode::PresentEarly;
            return recompui::renderer::create_render_context(rdram, window_handle, presentation_mode, developer_mode);
        },
    };

    ultramodern::gfx_callbacks_t gfx_callbacks{
        .create_gfx = create_gfx,
        .create_window = create_window,
        .update_gfx = update_gfx,
    };

    ultramodern::audio_callbacks_t audio_callbacks{
        .queue_samples = queue_samples,
        .get_frames_remaining = get_frames_remaining,
        .set_frequency = set_frequency,
    };

    ultramodern::input::callbacks_t input_callbacks{
        .poll_input = poll_input,
        .get_input = get_input,
        .set_rumble = set_rumble,
        .get_connected_device_info = get_connected_device_info,
    };

    ultramodern::events::callbacks_t events_callbacks{
        .vi_callback = nullptr,
        .gfx_init_callback = nullptr,
    };

    ultramodern::error_handling::callbacks_t error_handling_callbacks{
        .message_box = [](const char* msg) {
            fprintf(stderr, "Error: %s\n", msg);
            SDL_ShowSimpleMessageBox(SDL_MESSAGEBOX_ERROR, "Sin & Punishment: Recompiled", msg, nullptr);
        },
    };

    ultramodern::threads::callbacks_t threads_callbacks{
        .get_game_thread_name = [](const OSThread* t) -> std::string {
            return "[Game] " + std::to_string(t->id);
        },
    };

    recomp::Version project_version{};
    if (!recomp::Version::from_string(version_string, project_version)) {
        fprintf(stderr, "Invalid version string\n");
        return EXIT_FAILURE;
    }

    // Initialize program settings for recompui (must be set before any
    // recompui::file::* call, which uses the program id for paths).
    recompui::programconfig::set_program_name(program_name);
    recompui::programconfig::set_program_id(program_id);

    recomp::register_config_path(recompui::file::get_app_folder_path());

    for (const auto& game : supported_games) {
        recomp::register_game(game);
    }

    // Developer/testing hook: SP_AUTOSTART=1 starts the game immediately,
    // skipping the launcher (useful for automated boot testing).
    if (getenv("SP_AUTOSTART") != nullptr) {
        // The launcher normally runs the player-assignment flow (multiplayer mode).
        // When it is skipped, force single-player mode so that player 1 input works:
        // get_connected_device_info then reports a controller and get_n64_input uses
        // the SP keyboard/controller profiles (assigned by load_controls_config).
        recompinput::players::set_single_player_mode(true);
        recompui::register_launcher_init_callback([](recompui::LauncherMenu* menu) {
            (void)menu;
            recomp::start_game(supported_games[0].game_id, {});
        });
    }

    // Register fonts for recompui (must exist under assets/ next to the executable).
    recompui::register_primary_font("InterVariable.ttf", "Inter Variable");
    recompui::register_extra_font("NotoEmoji-Regular.ttf");

    // Initialize config (creates tabs + loads from disk).
    init_config();

    // Register the recompiled function section table (must precede recomp::start).
    register_snp_overlays();

    // Dev/test hook: SP_INPUT_SCRIPT=<file> (see input callbacks section).
    load_input_script();

    recomp::Configuration config{
        .project_version = project_version,
        .window_handle = {},
        .rsp_callbacks = rsp_callbacks,
        .renderer_callbacks = renderer_callbacks,
        .audio_callbacks = audio_callbacks,
        .input_callbacks = input_callbacks,
        .gfx_callbacks = gfx_callbacks,
        .events_callbacks = events_callbacks,
        .error_handling_callbacks = error_handling_callbacks,
        .threads_callbacks = threads_callbacks,
        .message_queue_control = {
            // NOTE: requeue_vi=true was tried but causes a pump busy-loop: with the game's
            // VI queue (0x800A326C, cap 8) full, the 1ms pump pops a VI message, do_send
            // fails, it's requeued, and the pump spins (tens of millions of log lines).
            // Dropping VI retraces is fine (game handles missed retraces).
            .requeue_vi = false,
            // SP completions (0x29B -> 0x800A32A4): drop-on-full like VI. With
            // requeue_sp=true (default), an SP-done message that cannot be inserted
            // because the queue is full gets requeued into the external-message queue
            // and re-popped by the pump's 1ms poll, producing an infinite extmsg/DROP
            // hot loop (snp_fix26.log: 670MB in ~25s). The game polls; a lost
            // completion is equivalent to a missed retrace on real hardware.
            .requeue_sp = false,
            // PI DMA completions must be requeued if the game's queue is momentarily full,
            // otherwise do_send drops them and the game hangs forever in osRecvMesg
            // (boot thread 3 waits on its sync-PI-DMA helper boot_func_8003A514).
            .requeue_pi = true,
        },
    };

    recomp::start(config);
    return EXIT_SUCCESS;
}
